/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculadora;

/**
 *
 * @author krazy
 */
public class Calculadora extends javax.swing.JFrame {

    private String cadenaNums = "";
    private String operacion = "nula";
    private double primerNum, resultado;
    private boolean activado = true;
    private boolean punto = true;
    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
        this.setTitle("Calculadora");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        botonC = new javax.swing.JButton();
        botonRaiz = new javax.swing.JButton();
        botonDividir = new javax.swing.JButton();
        botonPorcentaje = new javax.swing.JButton();
        boton7 = new javax.swing.JButton();
        boton8 = new javax.swing.JButton();
        boton9 = new javax.swing.JButton();
        botonX = new javax.swing.JButton();
        boton4 = new javax.swing.JButton();
        boton5 = new javax.swing.JButton();
        boton6 = new javax.swing.JButton();
        botonResta = new javax.swing.JButton();
        boton1 = new javax.swing.JButton();
        boton2 = new javax.swing.JButton();
        boton3 = new javax.swing.JButton();
        botonSuma = new javax.swing.JButton();
        botonPosNeg = new javax.swing.JButton();
        boton0 = new javax.swing.JButton();
        botonPunto = new javax.swing.JButton();
        botonIgual = new javax.swing.JButton();
        etiquetaNums = new javax.swing.JLabel();
        etiquetaMuestra = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel.setLayout(new java.awt.GridLayout(5, 4));

        botonC.setBackground(new java.awt.Color(108, 85, 103));
        botonC.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonC.setText("C");
        botonC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCActionPerformed(evt);
            }
        });
        panel.add(botonC);

        botonRaiz.setBackground(new java.awt.Color(131, 138, 150));
        botonRaiz.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonRaiz.setText("√ ");
        botonRaiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRaizActionPerformed(evt);
            }
        });
        panel.add(botonRaiz);

        botonDividir.setBackground(new java.awt.Color(131, 138, 150));
        botonDividir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonDividir.setText("/");
        botonDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDividirActionPerformed(evt);
            }
        });
        panel.add(botonDividir);

        botonPorcentaje.setBackground(new java.awt.Color(131, 138, 150));
        botonPorcentaje.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonPorcentaje.setText("%");
        botonPorcentaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPorcentajeActionPerformed(evt);
            }
        });
        panel.add(botonPorcentaje);

        boton7.setBackground(new java.awt.Color(191, 205, 218));
        boton7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        boton7.setText("7");
        boton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton7ActionPerformed(evt);
            }
        });
        panel.add(boton7);

        boton8.setBackground(new java.awt.Color(191, 205, 218));
        boton8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        boton8.setText("8");
        boton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton8ActionPerformed(evt);
            }
        });
        panel.add(boton8);

        boton9.setBackground(new java.awt.Color(191, 205, 218));
        boton9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        boton9.setText("9");
        boton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton9ActionPerformed(evt);
            }
        });
        panel.add(boton9);

        botonX.setBackground(new java.awt.Color(131, 138, 150));
        botonX.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonX.setText("*");
        botonX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonXActionPerformed(evt);
            }
        });
        panel.add(botonX);

        boton4.setBackground(new java.awt.Color(191, 205, 218));
        boton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        boton4.setText("4");
        boton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton4ActionPerformed(evt);
            }
        });
        panel.add(boton4);

        boton5.setBackground(new java.awt.Color(191, 205, 218));
        boton5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        boton5.setText("5");
        boton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton5ActionPerformed(evt);
            }
        });
        panel.add(boton5);

        boton6.setBackground(new java.awt.Color(191, 205, 218));
        boton6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        boton6.setText("6");
        boton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton6ActionPerformed(evt);
            }
        });
        panel.add(boton6);

        botonResta.setBackground(new java.awt.Color(131, 138, 150));
        botonResta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonResta.setText("-");
        botonResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRestaActionPerformed(evt);
            }
        });
        panel.add(botonResta);

        boton1.setBackground(new java.awt.Color(191, 205, 218));
        boton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        boton1.setText("1");
        boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton1ActionPerformed(evt);
            }
        });
        panel.add(boton1);

        boton2.setBackground(new java.awt.Color(191, 205, 218));
        boton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        boton2.setText("2");
        boton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton2ActionPerformed(evt);
            }
        });
        panel.add(boton2);

        boton3.setBackground(new java.awt.Color(191, 205, 218));
        boton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        boton3.setText("3");
        boton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton3ActionPerformed(evt);
            }
        });
        panel.add(boton3);

        botonSuma.setBackground(new java.awt.Color(131, 138, 150));
        botonSuma.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonSuma.setText("+");
        botonSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSumaActionPerformed(evt);
            }
        });
        panel.add(botonSuma);

        botonPosNeg.setBackground(new java.awt.Color(131, 138, 150));
        botonPosNeg.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonPosNeg.setText("+ / -");
        botonPosNeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPosNegActionPerformed(evt);
            }
        });
        panel.add(botonPosNeg);

        boton0.setBackground(new java.awt.Color(191, 205, 218));
        boton0.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        boton0.setText("0");
        boton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton0ActionPerformed(evt);
            }
        });
        panel.add(boton0);

        botonPunto.setBackground(new java.awt.Color(191, 205, 218));
        botonPunto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonPunto.setText(".");
        botonPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPuntoActionPerformed(evt);
            }
        });
        panel.add(botonPunto);

        botonIgual.setBackground(new java.awt.Color(65, 69, 78));
        botonIgual.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonIgual.setText("=");
        botonIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIgualActionPerformed(evt);
            }
        });
        panel.add(botonIgual);

        etiquetaNums.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        etiquetaNums.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiquetaNums.setText("0");

        etiquetaMuestra.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        etiquetaMuestra.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etiquetaNums, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiquetaMuestra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiquetaMuestra, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(etiquetaNums, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRaizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRaizActionPerformed
        primerNum = Double.parseDouble(cadenaNums);
        etiquetaMuestra.setText("√"+cadenaNums);
        resultado = Math.sqrt(primerNum);
        etiquetaNums.setText(String.format("%.2f", resultado));
        cadenaNums = String.valueOf(resultado); //Convertimos el valor a cadena
        punto = true;
    }//GEN-LAST:event_botonRaizActionPerformed

    private void boton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton7ActionPerformed
       if(etiquetaNums.getText().equals("0")){
           cadenaNums = "7"; //Se cambia el 0 por un 7
       }else{
           cadenaNums += "7"; //Se agrega un 7
       }
       etiquetaNums.setText(cadenaNums);
       activado = true; //Voy a usar la calculadora :)
    }//GEN-LAST:event_boton7ActionPerformed

    private void boton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton8ActionPerformed
       if(etiquetaNums.getText().equals("0")){
           cadenaNums = "8"; 
       }else{
           cadenaNums += "8";
       }
       etiquetaNums.setText(cadenaNums);
       activado = true;
    }//GEN-LAST:event_boton8ActionPerformed

    private void boton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton9ActionPerformed
        if(etiquetaNums.getText().equals("0")){
           cadenaNums = "9"; 
       }else{
           cadenaNums += "9";
       }
       etiquetaNums.setText(cadenaNums);
       activado = true;
    }//GEN-LAST:event_boton9ActionPerformed

    private void boton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton6ActionPerformed
        if(etiquetaNums.getText().equals("0")){
           cadenaNums = "6"; 
       }else{
           cadenaNums += "6";
       }
       etiquetaNums.setText(cadenaNums);
       activado = true;
    }//GEN-LAST:event_boton6ActionPerformed

    private void boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton1ActionPerformed
        if(etiquetaNums.getText().equals("0")){
           cadenaNums = "1"; 
       }else{
           cadenaNums += "1";
       }
       etiquetaNums.setText(cadenaNums);
       activado = true;
    }//GEN-LAST:event_boton1ActionPerformed

    private void boton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton2ActionPerformed
        if(etiquetaNums.getText().equals("0")){
           cadenaNums = "2"; 
       }else{
           cadenaNums += "2";
       }
       etiquetaNums.setText(cadenaNums);
       activado = true;
    }//GEN-LAST:event_boton2ActionPerformed

    private void boton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton3ActionPerformed
        if(etiquetaNums.getText().equals("0")){
           cadenaNums = "3"; 
       }else{
           cadenaNums += "3";
       }
       etiquetaNums.setText(cadenaNums);
       activado = true;
    }//GEN-LAST:event_boton3ActionPerformed

    private void boton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton4ActionPerformed
        if(etiquetaNums.getText().equals("0")){
           cadenaNums = "4"; 
       }else{
           cadenaNums += "4";
       }
       etiquetaNums.setText(cadenaNums);
       activado = true;
    }//GEN-LAST:event_boton4ActionPerformed

    private void boton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton5ActionPerformed
        if(etiquetaNums.getText().equals("0")){
           cadenaNums = "5"; 
       }else{
           cadenaNums += "5";
       }
       etiquetaNums.setText(cadenaNums);
       activado = true;
    }//GEN-LAST:event_boton5ActionPerformed

    private void boton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton0ActionPerformed
        if(etiquetaNums.getText().equals("0")){
           cadenaNums = "0"; 
       }else{
           cadenaNums += "0";
       }
       etiquetaNums.setText(cadenaNums);
       activado = true;
    }//GEN-LAST:event_boton0ActionPerformed

    private void botonSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSumaActionPerformed
        if(activado == true){
            primerNum = Double.parseDouble(cadenaNums);
            etiquetaMuestra.setText(cadenaNums + " + ");
            cadenaNums = "";
            operacion = "sumar";
            
            activado = false;        }
    }//GEN-LAST:event_botonSumaActionPerformed

    private void botonIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIgualActionPerformed
        double segundoNum;
        if(operacion.equals("nula")){
            etiquetaNums.setText(cadenaNums);
        }
        
        else if(operacion.equals("sumar")){
            segundoNum = Double.parseDouble(cadenaNums);
            resultado = primerNum + segundoNum;
            etiquetaNums.setText(String.format("% .2f", resultado));
            cadenaNums = String.valueOf(resultado); //Convirtiendo Double a String
            operacion = "nula";
        }
        
        else if(operacion.equals("restar")){
            segundoNum = Double.parseDouble(cadenaNums);
            resultado = primerNum - segundoNum;
            etiquetaNums.setText(String.format("% .2f", resultado));
            cadenaNums = String.valueOf(resultado); //Convirtiendo Double a String
            operacion = "nula";
        }
        
        else if(operacion.equals("multiplicar")){
            segundoNum = Double.parseDouble(cadenaNums);
            resultado = primerNum * segundoNum;
            etiquetaNums.setText(String.format("% .2f", resultado));
            cadenaNums = String.valueOf(resultado); //Convirtiendo Double a String
            operacion = "nula";
        }
        
        else if(operacion.equals("dividir")){
            segundoNum = Double.parseDouble(cadenaNums);
            if(segundoNum == 0){
                etiquetaNums.setText("No es posible dividir entre 0");
            }else{
                resultado = primerNum / segundoNum;
                etiquetaNums.setText(String.format("% .2f", resultado));
                cadenaNums = String.valueOf(resultado); //Convirtiendo Double a String
                operacion = "nula";
            }
        }
        
        else if(operacion.equals("porcentaje")){
            segundoNum = Double.parseDouble(cadenaNums);
            resultado = (primerNum * segundoNum)/100;
            etiquetaNums.setText(String.format("% .2f", resultado));
            cadenaNums = String.valueOf(resultado); //Convirtiendo Double a String
            operacion = "nula";
        }
        
        
        etiquetaMuestra.setText("");
        activado = true;
        punto = false;
    }//GEN-LAST:event_botonIgualActionPerformed

    private void botonXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonXActionPerformed
        if(activado == true){
            primerNum = Double.parseDouble(cadenaNums);
            etiquetaMuestra.setText(cadenaNums + " * ");
            cadenaNums = "";
            operacion = "multiplicar";
            
            activado = false;
        }
    }//GEN-LAST:event_botonXActionPerformed

    private void botonRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRestaActionPerformed
        if(activado == true){
            primerNum = Double.parseDouble(cadenaNums);
            etiquetaMuestra.setText(cadenaNums + " - ");
            cadenaNums = "";
            operacion = "restar";
            
            activado = false;
        }
    }//GEN-LAST:event_botonRestaActionPerformed

    private void botonDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDividirActionPerformed
        if(activado == true){
            primerNum = Double.parseDouble(cadenaNums);
            etiquetaMuestra.setText(cadenaNums + " / ");
            cadenaNums = "";
            operacion = "dividir";
            
            activado = false;
        }
    }//GEN-LAST:event_botonDividirActionPerformed

    private void botonPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPuntoActionPerformed
        if(punto == true){
            if(cadenaNums.equals("")){ //Si esta vacio, se añade a la cadena el 0.
                cadenaNums = "0.";
            }else{
                cadenaNums += "."; //Si tiene un valor, se añade el punto a la cadena
            }
            etiquetaNums.setText(cadenaNums);
            punto = false;
        }
    }//GEN-LAST:event_botonPuntoActionPerformed

    private void botonPosNegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPosNegActionPerformed
        if(cadenaNums.charAt(0) != '-'){ //Si la primer letra de la cadena no tiene un menos, se le agrega el menos, haciendo el numero negativo
            cadenaNums = "-" + cadenaNums;
        }else{ //Caso contrario, al tener un signo de menos, se le quita el primer elemento de la cadena, o sea el signo de menos, gracias al substring
            cadenaNums = cadenaNums.substring(1, cadenaNums.length()); 
        }
        etiquetaNums.setText(cadenaNums);
    }//GEN-LAST:event_botonPosNegActionPerformed

    private void botonCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCActionPerformed
        etiquetaMuestra.setText("");
        etiquetaNums.setText("0");
        operacion = "nula";
        cadenaNums = "";
        activado = true;
        punto = true;
    }//GEN-LAST:event_botonCActionPerformed

    private void botonPorcentajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPorcentajeActionPerformed
        if(activado == true){
            primerNum = Double.parseDouble(cadenaNums);
            etiquetaMuestra.setText(cadenaNums + " % ");
            cadenaNums = "";
            operacion = "porcentaje";
            
            activado = false;
        }
    }//GEN-LAST:event_botonPorcentajeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton0;
    private javax.swing.JButton boton1;
    private javax.swing.JButton boton2;
    private javax.swing.JButton boton3;
    private javax.swing.JButton boton4;
    private javax.swing.JButton boton5;
    private javax.swing.JButton boton6;
    private javax.swing.JButton boton7;
    private javax.swing.JButton boton8;
    private javax.swing.JButton boton9;
    private javax.swing.JButton botonC;
    private javax.swing.JButton botonDividir;
    private javax.swing.JButton botonIgual;
    private javax.swing.JButton botonPorcentaje;
    private javax.swing.JButton botonPosNeg;
    private javax.swing.JButton botonPunto;
    private javax.swing.JButton botonRaiz;
    private javax.swing.JButton botonResta;
    private javax.swing.JButton botonSuma;
    private javax.swing.JButton botonX;
    private javax.swing.JLabel etiquetaMuestra;
    private javax.swing.JLabel etiquetaNums;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
